/*
Copyright 2018 The Knative Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/knative/pkg/apis/duck/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeLegacyTargets implements LegacyTargetInterface
type FakeLegacyTargets struct {
	Fake *FakeDuckV1alpha1
	ns   string
}

var legacytargetsResource = schema.GroupVersionResource{Group: "duck.knative.dev", Version: "v1alpha1", Resource: "legacytargets"}

var legacytargetsKind = schema.GroupVersionKind{Group: "duck.knative.dev", Version: "v1alpha1", Kind: "LegacyTarget"}

// Get takes name of the legacyTarget, and returns the corresponding legacyTarget object, and an error if there is any.
func (c *FakeLegacyTargets) Get(name string, options v1.GetOptions) (result *v1alpha1.LegacyTarget, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(legacytargetsResource, c.ns, name), &v1alpha1.LegacyTarget{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.LegacyTarget), err
}

// List takes label and field selectors, and returns the list of LegacyTargets that match those selectors.
func (c *FakeLegacyTargets) List(opts v1.ListOptions) (result *v1alpha1.LegacyTargetList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(legacytargetsResource, legacytargetsKind, c.ns, opts), &v1alpha1.LegacyTargetList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.LegacyTargetList{ListMeta: obj.(*v1alpha1.LegacyTargetList).ListMeta}
	for _, item := range obj.(*v1alpha1.LegacyTargetList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested legacyTargets.
func (c *FakeLegacyTargets) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(legacytargetsResource, c.ns, opts))

}

// Create takes the representation of a legacyTarget and creates it.  Returns the server's representation of the legacyTarget, and an error, if there is any.
func (c *FakeLegacyTargets) Create(legacyTarget *v1alpha1.LegacyTarget) (result *v1alpha1.LegacyTarget, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(legacytargetsResource, c.ns, legacyTarget), &v1alpha1.LegacyTarget{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.LegacyTarget), err
}

// Update takes the representation of a legacyTarget and updates it. Returns the server's representation of the legacyTarget, and an error, if there is any.
func (c *FakeLegacyTargets) Update(legacyTarget *v1alpha1.LegacyTarget) (result *v1alpha1.LegacyTarget, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(legacytargetsResource, c.ns, legacyTarget), &v1alpha1.LegacyTarget{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.LegacyTarget), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeLegacyTargets) UpdateStatus(legacyTarget *v1alpha1.LegacyTarget) (*v1alpha1.LegacyTarget, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(legacytargetsResource, "status", c.ns, legacyTarget), &v1alpha1.LegacyTarget{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.LegacyTarget), err
}

// Delete takes name of the legacyTarget and deletes it. Returns an error if one occurs.
func (c *FakeLegacyTargets) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(legacytargetsResource, c.ns, name), &v1alpha1.LegacyTarget{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeLegacyTargets) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(legacytargetsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.LegacyTargetList{})
	return err
}

// Patch applies the patch and returns the patched legacyTarget.
func (c *FakeLegacyTargets) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.LegacyTarget, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(legacytargetsResource, c.ns, name, data, subresources...), &v1alpha1.LegacyTarget{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.LegacyTarget), err
}
