/*
Copyright 2018 The Knative Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/knative/pkg/apis/duck/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeSubscribables implements SubscribableInterface
type FakeSubscribables struct {
	Fake *FakeDuckV1alpha1
	ns   string
}

var subscribablesResource = schema.GroupVersionResource{Group: "duck.knative.dev", Version: "v1alpha1", Resource: "subscribables"}

var subscribablesKind = schema.GroupVersionKind{Group: "duck.knative.dev", Version: "v1alpha1", Kind: "Subscribable"}

// Get takes name of the subscribable, and returns the corresponding subscribable object, and an error if there is any.
func (c *FakeSubscribables) Get(name string, options v1.GetOptions) (result *v1alpha1.Subscribable, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(subscribablesResource, c.ns, name), &v1alpha1.Subscribable{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Subscribable), err
}

// List takes label and field selectors, and returns the list of Subscribables that match those selectors.
func (c *FakeSubscribables) List(opts v1.ListOptions) (result *v1alpha1.SubscribableList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(subscribablesResource, subscribablesKind, c.ns, opts), &v1alpha1.SubscribableList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.SubscribableList{ListMeta: obj.(*v1alpha1.SubscribableList).ListMeta}
	for _, item := range obj.(*v1alpha1.SubscribableList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested subscribables.
func (c *FakeSubscribables) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(subscribablesResource, c.ns, opts))

}

// Create takes the representation of a subscribable and creates it.  Returns the server's representation of the subscribable, and an error, if there is any.
func (c *FakeSubscribables) Create(subscribable *v1alpha1.Subscribable) (result *v1alpha1.Subscribable, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(subscribablesResource, c.ns, subscribable), &v1alpha1.Subscribable{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Subscribable), err
}

// Update takes the representation of a subscribable and updates it. Returns the server's representation of the subscribable, and an error, if there is any.
func (c *FakeSubscribables) Update(subscribable *v1alpha1.Subscribable) (result *v1alpha1.Subscribable, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(subscribablesResource, c.ns, subscribable), &v1alpha1.Subscribable{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Subscribable), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeSubscribables) UpdateStatus(subscribable *v1alpha1.Subscribable) (*v1alpha1.Subscribable, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(subscribablesResource, "status", c.ns, subscribable), &v1alpha1.Subscribable{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Subscribable), err
}

// Delete takes name of the subscribable and deletes it. Returns an error if one occurs.
func (c *FakeSubscribables) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(subscribablesResource, c.ns, name), &v1alpha1.Subscribable{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeSubscribables) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(subscribablesResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.SubscribableList{})
	return err
}

// Patch applies the patch and returns the patched subscribable.
func (c *FakeSubscribables) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.Subscribable, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(subscribablesResource, c.ns, name, data, subresources...), &v1alpha1.Subscribable{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Subscribable), err
}
