/*
Copyright 2018 The Knative Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/knative/pkg/apis/duck/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeChannelableReves implements ChannelableRefInterface
type FakeChannelableReves struct {
	Fake *FakeDuckV1alpha1
	ns   string
}

var channelablerevesResource = schema.GroupVersionResource{Group: "duck.knative.dev", Version: "v1alpha1", Resource: "channelablereves"}

var channelablerevesKind = schema.GroupVersionKind{Group: "duck.knative.dev", Version: "v1alpha1", Kind: "ChannelableRef"}

// Get takes name of the channelableRef, and returns the corresponding channelableRef object, and an error if there is any.
func (c *FakeChannelableReves) Get(name string, options v1.GetOptions) (result *v1alpha1.ChannelableRef, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(channelablerevesResource, c.ns, name), &v1alpha1.ChannelableRef{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ChannelableRef), err
}

// List takes label and field selectors, and returns the list of ChannelableReves that match those selectors.
func (c *FakeChannelableReves) List(opts v1.ListOptions) (result *v1alpha1.ChannelableRefList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(channelablerevesResource, channelablerevesKind, c.ns, opts), &v1alpha1.ChannelableRefList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ChannelableRefList{ListMeta: obj.(*v1alpha1.ChannelableRefList).ListMeta}
	for _, item := range obj.(*v1alpha1.ChannelableRefList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested channelableReves.
func (c *FakeChannelableReves) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(channelablerevesResource, c.ns, opts))

}

// Create takes the representation of a channelableRef and creates it.  Returns the server's representation of the channelableRef, and an error, if there is any.
func (c *FakeChannelableReves) Create(channelableRef *v1alpha1.ChannelableRef) (result *v1alpha1.ChannelableRef, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(channelablerevesResource, c.ns, channelableRef), &v1alpha1.ChannelableRef{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ChannelableRef), err
}

// Update takes the representation of a channelableRef and updates it. Returns the server's representation of the channelableRef, and an error, if there is any.
func (c *FakeChannelableReves) Update(channelableRef *v1alpha1.ChannelableRef) (result *v1alpha1.ChannelableRef, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(channelablerevesResource, c.ns, channelableRef), &v1alpha1.ChannelableRef{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ChannelableRef), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeChannelableReves) UpdateStatus(channelableRef *v1alpha1.ChannelableRef) (*v1alpha1.ChannelableRef, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(channelablerevesResource, "status", c.ns, channelableRef), &v1alpha1.ChannelableRef{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ChannelableRef), err
}

// Delete takes name of the channelableRef and deletes it. Returns an error if one occurs.
func (c *FakeChannelableReves) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(channelablerevesResource, c.ns, name), &v1alpha1.ChannelableRef{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeChannelableReves) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(channelablerevesResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.ChannelableRefList{})
	return err
}

// Patch applies the patch and returns the patched channelableRef.
func (c *FakeChannelableReves) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.ChannelableRef, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(channelablerevesResource, c.ns, name, data, subresources...), &v1alpha1.ChannelableRef{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ChannelableRef), err
}
